const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..');
const core = fs.readFileSync(path.join(root, 'src/core.js'), 'utf8');
const version = core.match(/var VERSION = '([^']+)'/)[1];
const defaults = {
  provider: 'google', deeplKey: '', deeplApiHost: 'api-free.deepl.com',
  geminiKey: '', geminiModel: 'gemini-3.8-flash', deepseekKey: '', deepseekModel: 'deepseek-flash'
};
const banner = '/* NewsBilingual ' + version + ' | Quantumult X | Generated by tools/build.cjs\n' +
  ' * Local use: fill keys below. Remote use: BoxJS preferences override these values.\n' +
  ' * Never upload a file containing real API keys to a public host.\n */\n';
const bundle = banner + '(function () {\nvar LOCAL_CONFIG = ' + JSON.stringify(defaults, null, 2) + ';\n' +
  fs.readFileSync(path.join(root, 'src/browser.js'), 'utf8') + '\n' + core + '\n})();\n';
fs.writeFileSync(path.join(root, 'NewsBilingual.js'), bundle);
function snippet(script) {
  const domain = '^https:\\/\\/(?:(?:www\\.)?(?:wsj\\.com|nytimes\\.com|economist\\.com)|(?:www\\.|app\\.)?ft\\.com)(?::443)?';
  return '#!name=NewsBilingual 新闻双语（HTML / WebView）\n#!desc=点击双语；Google / DeepL / Gemini / DeepSeek。支持 NYT App GraphQL 正文。\n#!version=' + version + '\n' +
    'hostname = wsj.com, www.wsj.com, nytimes.com, www.nytimes.com, samizdat-graphql.nytimes.com, ft.com, www.ft.com, app.ft.com, economist.com, www.economist.com\n\n' +
    domain + '\\/__news_bilingual__\\/v2\\/translate(?:\\?.*)?$ url script-analyze-echo-response ' + script + '\n' +
    domain + '\\/__news_bilingual__\\/v2\\/(?:client\\.js|status|diagnostic)(?:\\?.*)?$ url script-echo-response ' + script + '\n' +
    '^https:\\/\\/samizdat-graphql\\.nytimes\\.com(?::443)?\\/graphql\\/v2\\?(?:[^#]*&)?operationName=Asset(?:&[^#]*)?$ url script-response-body ' + script + '\n' +
    domain + '\\/(?!__news_bilingual__\\/)(?!_{1,2}origami\\/service\\/image\\/)(?!_next\\/|vi-assets\\/|assets?\\/|static\\/|images?\\/|fonts?\\/|videos?\\/)(?![^?#]*\\.(?:avif|bmp|css|gif|ico|jpe?g|js|m4a|m4v|mov|mp3|mp4|m3u8|pdf|png|svg|ttf|webm|webp|woff2?)(?:[?#]|$)) url script-response-body ' + script + '\n';
}
fs.writeFileSync(path.join(root, 'NewsBilingual.snippet'), snippet('NewsBilingual.js'));
const base = process.argv[2];
if (base) {
  const url = new URL(base);
  if (url.protocol !== 'https:' || url.username || url.password || url.search || url.hash || /\s/.test(base)) throw new Error('Use a public HTTPS directory URL without credentials/query/fragment');
  fs.writeFileSync(path.join(root, 'NewsBilingual.remote.snippet'), snippet(base.replace(/\/$/, '') + '/NewsBilingual.js?v=' + version));
}
const names = {provider: '默认翻译服务', deeplKey: 'DeepL API Key', deeplApiHost: 'DeepL API 主机',
  geminiKey: 'Gemini API Key', geminiModel: 'Gemini 模型', deepseekKey: 'DeepSeek API Key', deepseekModel: 'DeepSeek 模型'};
const box = {id: 'NewsBilingual.subscription', name: 'NewsBilingual 新闻双语', apps: [{id: 'NewsBilingual', name: 'NewsBilingual 新闻双语',
  descs_html: ['Google 默认免 Key；其他服务填写后保存。配置保存在 Quantumult X 本机。'],
  keys: Object.keys(defaults).map(k => 'NewsBilingual.' + k), settings: Object.keys(defaults).map(k => ({
    id: 'NewsBilingual.' + k, name: names[k], type: 'text', val: defaults[k],
    desc: k === 'provider' ? 'google / deepl / gemini / deepseek' : k === 'deeplApiHost' ? '免费 api-free.deepl.com；付费 api.deepl.com' : ''
  }))}]};
box.apps[0].settings.find(s => s.id === 'NewsBilingual.provider').type = 'selects';
box.apps[0].settings.find(s => s.id === 'NewsBilingual.provider').items = ['google', 'deepl', 'gemini', 'deepseek'].map(key => ({key, label: key}));
fs.writeFileSync(path.join(root, 'NewsBilingual.boxjs.json'), JSON.stringify(box, null, 2) + '\n');
console.log('Built NewsBilingual.js, local snippet and optional BoxJS settings' + (base ? ', remote snippet' : ''));
